<a href="https://colab.research.google.com/github/nagalingamakhil/SQLPROJ/blob/main/Akhil_SQL_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!apt-get install sqlite3 -y
!pip install pandas tabulate

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  sqlite3-doc
The following NEW packages will be installed:
  sqlite3
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 144 kB of archives.
After this operation, 584 kB of additional disk space will be used.
Ign:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 sqlite3 amd64 3.45.1-1ubuntu2.7
Err:1 http://security.ubuntu.com/ubuntu noble-updates/main amd64 sqlite3 amd64 3.45.1-1ubuntu2.7
  404  Not Found [IP: 91.189.91.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/sqlite3/sqlite3_3.45.1-1ubuntu2.7_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.13/dist-packages (0.9.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import sqlite3
import pandas as pd
import os

In [ ]:
conn = sqlite3.connect("my_database (2) (1).db")

In [ ]:
db_path='/content/drive/MyDrive/my_database (2) (1).db'

In [ ]:
db_folder ="/content/drive/MyDrive/SQLPROJ"
os.makedirs(db_folder, exist_ok=True)  # Ensure the folder exists
db_path = os.path.join(db_folder, "my_database (2) (1).db")# joining my folder to my file

In [ ]:
conn = sqlite3.connect(db_path)
cursor =conn.cursor()
print("database at ",db_path)

database at  /content/drive/MyDrive/SQLPROJ/my_database (2) (1).db

In [ ]:
tables_to_delete = [
    "BANK_CUSTOMER",
    "BANK_CUSTOMER_EXPORT",
    "BANK_ACCOUNT_DETAILS",
    "BANK_ACCOUNT",
    "BANK_ACCOUNT_RELATIONSHIP_DETAILS",
    "BANK_ACCOUNT_TRANSACTION",
    "BANK_CUSTOMER_MESSAGES",
    "BANK_INTEREST_RATE",
    "BANK_CUSTOM1R"
]

for table in tables_to_delete:
    cursor.execute(f"DROP TABLE IF EXISTS {table}")

conn.commit()

print("Old tables removed successfully.")

Old tables removed successfully.

In [ ]:
cursor.execute('''

CREATE TABLE BANK_CUSTOMER (
    customer_id INT,
    customer_name VARCHAR(20),
    Address VARCHAR(20),
    state_code VARCHAR(3),
    Telephone VARCHAR(10)
);

''')

conn.commit()

print("BANK_CUSTOMER table created successfully!")

BANK_CUSTOMER table created successfully!

In [ ]:
def insert_BANK_CUSTOMER(customer_id, customer_name, Address, state_code, Telephone):

    cursor.execute("""
    INSERT INTO BANK_CUSTOMER
    (customer_id, customer_name, Address, state_code, Telephone)
    VALUES (?, ?, ?, ?, ?)
    """,
    (customer_id, customer_name, Address, state_code, Telephone))

    conn.commit()

In [ ]:
insert_BANK_CUSTOMER(123001, "Oliver", "225-5, Emeryville", "CA", "1897614500")
insert_BANK_CUSTOMER(123002, "George", "194-6,New brighton", "MN", "1897617000")
insert_BANK_CUSTOMER(123003, "Harry", "2909-5,walnut creek", "CA", "1897617866")
insert_BANK_CUSTOMER(123004, "Jack", "229-5, Concord", "CA", "1897627999")
insert_BANK_CUSTOMER(123005, "Jacob", "325-7, Mission Dist", "SFO", "1897637000")
insert_BANK_CUSTOMER(123006, "Noah", "275-9, saint-paul", "MN", "1897613200")
insert_BANK_CUSTOMER(123007, "Charlie", "125-1,Richfield", "MN", "1897617666")
insert_BANK_CUSTOMER(123008, "Robin", "3005-1,Heathrow", "NY", "1897614000")

print("BANK_CUSTOMER table created and data inserted successfully.")

BANK_CUSTOMER table created and data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM BANK_CUSTOMER", conn)
display(df)

   customer_id customer_name              Address state_code   Telephone
0       123001        Oliver    225-5, Emeryville         CA  1897614500
1       123002        George   194-6,New brighton         MN  1897617000
2       123003         Harry  2909-5,walnut creek         CA  1897617866
3       123004          Jack       229-5, Concord         CA  1897627999
4       123005         Jacob  325-7, Mission Dist        SFO  1897637000
5       123006          Noah    275-9, saint-paul         MN  1897613200
6       123007       Charlie      125-1,Richfield         MN  1897617666
7       123008         Robin      3005-1,Heathrow         NY  1897614000

In [ ]:
cursor.execute('''
CREATE TABLE BANK_CUSTOMER_EXPORT (
    customer_id CHAR(10),
    customer_name CHAR(20),
    Address CHAR(20),
    state_code CHAR(3),
    Telephone CHAR(10)
);
''')

conn.commit()

In [ ]:
print("BANK_CUSTOMER_EXPORT table created successfully!")

BANK_CUSTOMER_EXPORT table created successfully!

In [ ]:
def insert_BANK_CUSTOMER_EXPORT(customer_id, customer_name, Address, state_code, Telephone):
    cursor.execute("INSERT INTO BANK_CUSTOMER_EXPORT VALUES (?, ?, ?, ?, ?)", (customer_id, customer_name, Address, state_code, Telephone))
    conn.commit()

In [ ]:
insert_BANK_CUSTOMER_EXPORT("123001 ", "Oliver", "225-5, Emeryville", "CA", "1897614500")
insert_BANK_CUSTOMER_EXPORT("123002 ", "George", "194-6,New brighton", "MN", "189761700")

In [ ]:
print("BANK_CUSTOMER_EXPORT table data inserted successfully.")

BANK_CUSTOMER_EXPORT table data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM BANK_CUSTOMER_EXPORT", conn)
display(df)

  customer_id customer_name             Address state_code   Telephone
0     123001         Oliver   225-5, Emeryville         CA  1897614500
1     123002         George  194-6,New brighton         MN   189761700

In [ ]:
cursor.execute('''
CREATE TABLE Bank_Account_Details (
    Customer_id INT,
    Account_Number VARCHAR(19),
    Account_type VARCHAR(25),
    Balance_amount INT,
    Account_status VARCHAR(10),
    Relationship_type VARCHAR(1)
);
''')

conn.commit()

In [ ]:
print("Bank_Account_Details table created successfully!")

Bank_Account_Details table created successfully!

In [ ]:
def insert_Bank_Account_Details(Customer_id, Account_Number, Account_type, Balance_amount, Account_status, Relationship_type):
    cursor.execute("INSERT INTO Bank_Account_Details VALUES (?, ?, ?, ?, ?, ?)", (Customer_id, Account_Number, Account_type, Balance_amount, Account_status, Relationship_type))
    conn.commit()

In [ ]:
insert_Bank_Account_Details(123001, "4000-1956-3456", "SAVINGS", 200000, "ACTIVE", "P")
insert_Bank_Account_Details(123001, "5000-1700-3456", "RECURRING DEPOSITS", 9400000, "ACTIVE", "S")
insert_Bank_Account_Details(123002, "4000-1956-2001", "SAVINGS", 400000, "ACTIVE", "P")
insert_Bank_Account_Details(123002, "5000-1700-5001", "RECURRING DEPOSITS", 7500000, "ACTIVE", "S")
insert_Bank_Account_Details(123003, "4000-1956-2900", "SAVINGS", 750000, "INACTIVE", "P")
insert_Bank_Account_Details(123004, "5000-1700-6091", "RECURRING DEPOSITS", 7500000, "ACTIVE", "S")
insert_Bank_Account_Details(123004, "4000-1956-3401", "SAVINGS", 655000, "ACTIVE", "P")
insert_Bank_Account_Details(123005, "4000-1956-5102", "SAVINGS", 300000, "ACTIVE", "P")
insert_Bank_Account_Details(123006, "4000-1956-5698", "SAVINGS", 455000, "ACTIVE", "P")
insert_Bank_Account_Details(123007, "5000-1700-9800", "SAVINGS", 355000, "ACTIVE", "P")
insert_Bank_Account_Details(123007, "4000-1956-9977", "RECURRING DEPOSITS", 7025000, "ACTIVE", "S")
insert_Bank_Account_Details(123007, "9000-1700-7777-4321", "Credit Card", 0, "INACTIVE", "P")
insert_Bank_Account_Details(123007, "5900-1900-9877-5543", "Add-on Credit Card", 0, "ACTIVE", "S")
insert_Bank_Account_Details(123008, "5000-1700-7755", "SAVINGS", 0, "INACTIVE", "P")
insert_Bank_Account_Details(123006, "5800-1700-9800-7755", "Credit Card", 0, "ACTIVE", "P")
insert_Bank_Account_Details(123006, "5890-1970-7706-8912", "Add-on Credit Card", 0, "ACTIVE", "S")

print("Bank_Account_Details table  data inserted successfully.")

Bank_Account_Details table  data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM Bank_Account_Details", conn)
display(df)

,Customer_id,Account_Number,Account_type,Balance_amount,Account_status,Relationship_type
0,123001,4000-1956-3456,SAVINGS,200000,ACTIVE,P
1,123001,5000-1700-3456,RECURRING DEPOSITS,9400000,ACTIVE,S
2,123002,4000-1956-2001,SAVINGS,400000,ACTIVE,P
3,123002,5000-1700-5001,RECURRING DEPOSITS,7500000,ACTIVE,S
4,123003,4000-1956-2900,SAVINGS,750000,INACTIVE,P
5,123004,5000-1700-6091,RECURRING DEPOSITS,7500000,ACTIVE,S
6,123004,4000-1956-3401,SAVINGS,655000,ACTIVE,P
7,123005,4000-1956-5102,SAVINGS,300000,ACTIVE,P
8,123006,4000-1956-5698,SAVINGS,455000,ACTIVE,P
9,123007,5000-1700-9800,SAVINGS,355000,ACTIVE,P
10,123007,4000-1956-9977,RECURRING DEPOSITS,7025000,ACTIVE,S
11,123007,9000-1700-7777-4321,Credit Card,0,INACTIVE,P
12,123007,5900-1900-9877-5543,Add-on Credit Card,0,ACTIVE,S
13,123008,5000-1700-7755,SAVINGS,0,INACTIVE,P
14,123006,5800-1700-9800-7755,Credit Card,0,ACTIVE,P
15,123006,5890-1970-7706-8912,Add-on Credit Card,0,ACTIVE,S

In [ ]:
cursor.execute('''
CREATE TABLE BANK_ACCOUNT (
    Customer_id INT,
    Account_Number VARCHAR(19),
    Account_type VARCHAR(25),
    Balance_amount INT,
    Account_status VARCHAR(10),
    Relation_ship VARCHAR(1)
);
''')

conn.commit()

In [ ]:
print("BANK_ACCOUNT table created successfully!")

BANK_ACCOUNT table created successfully!

In [ ]:
def insert_BANK_ACCOUNT(Customer_id, Account_Number, Account_type, Balance_amount, Account_status, Relation_ship):
    cursor.execute("INSERT INTO BANK_ACCOUNT VALUES (?, ?, ?, ?, ?, ?)", (Customer_id, Account_Number, Account_type, Balance_amount, Account_status, Relation_ship))
    conn.commit()

In [ ]:
insert_BANK_ACCOUNT(123001, "4000-1956-3456", "SAVINGS", 200000, "ACTIVE", "P")
insert_BANK_ACCOUNT(123001, "5000-1700-3456", "RECURRING DEPOSITS", 9400000, "ACTIVE", "S")
insert_BANK_ACCOUNT(123002, "4000-1956-2001", "SAVINGS", 400000, "ACTIVE", "P")
insert_BANK_ACCOUNT(123002, "5000-1700-5001", "RECURRING DEPOSITS", 7500000, "ACTIVE", "S")
insert_BANK_ACCOUNT(123003, "4000-1956-2900", "SAVINGS", 750000, "INACTIVE", "P")
insert_BANK_ACCOUNT(123004, "5000-1700-6091", "RECURRING DEPOSITS", 7500000, "ACTIVE", "S")
insert_BANK_ACCOUNT(123004, "4000-1956-3401", "SAVINGS", 655000, "ACTIVE", "P")
insert_BANK_ACCOUNT(123005, "4000-1956-5102", "SAVINGS", 300000, "ACTIVE", "P")
insert_BANK_ACCOUNT(123006, "4000-1956-5698", "SAVINGS", 455000, "ACTIVE", "P")
insert_BANK_ACCOUNT(123007, "5000-1700-9800", "SAVINGS", 355000, "ACTIVE", "P")
insert_BANK_ACCOUNT(123007, "4000-1956-9977", "RECURRING DEPOSITS", 7025000, "ACTIVE", "S")
insert_BANK_ACCOUNT(123007, "9000-1700-7777-4321", "CREDITCARD", 0, "INACTIVE", "P")
insert_BANK_ACCOUNT(123008, "5000-1700-7755", "SAVINGS", None, "INACTIVE", "P")

print("BANK_ACCOUNT table data inserted successfully.")

BANK_ACCOUNT table data inserted successfully.

In [ ]:
cursor.execute('''
CREATE TABLE Bank_Account_Relationship_Details (
    Customer_id INT,
    Account_Number VARCHAR(19),
    Account_type VARCHAR(25),
    Linking_Account_Number VARCHAR(19)
);
''')

conn.commit()

In [ ]:
print("Bank_Account_Relationship_Details table created successfully!")

Bank_Account_Relationship_Details table created successfully!

In [ ]:
def insert_Bank_Account_Relationship_Details(Customer_id, Account_Number, Account_type, Linking_Account_Number):
    cursor.execute("INSERT INTO Bank_Account_Relationship_Details VALUES (?, ?, ?, ?)", (Customer_id, Account_Number, Account_type, Linking_Account_Number))
    conn.commit()

In [ ]:
insert_Bank_Account_Relationship_Details(123001, "4000-1956-3456", "SAVINGS", "")
insert_Bank_Account_Relationship_Details(123001, "5000-1700-3456", "RECURRING DEPOSITS", "4000-1956-3456")
insert_Bank_Account_Relationship_Details(123002, "4000-1956-2001", "SAVINGS", "")
insert_Bank_Account_Relationship_Details(123002, "5000-1700-5001", "RECURRING DEPOSITS", "4000-1956-2001")
insert_Bank_Account_Relationship_Details(123003, "4000-1956-2900", "SAVINGS", "")
insert_Bank_Account_Relationship_Details(123004, "5000-1700-6091", "RECURRING DEPOSITS", "4000-1956-2900")
insert_Bank_Account_Relationship_Details(123004, "5000-1700-7791", "RECURRING DEPOSITS", "4000-1956-2900")
insert_Bank_Account_Relationship_Details(123007, "5000-1700-9800", "SAVINGS", "")
insert_Bank_Account_Relationship_Details(123007, "4000-1956-9977", "RECURRING DEPOSITS", "5000-1700-9800")
insert_Bank_Account_Relationship_Details(None, "9000-1700-7777-4321", "Credit Card", "5000-1700-9800")
insert_Bank_Account_Relationship_Details(None, "5900-1900-9877-5543", "Add-on Credit Card", "9000-1700-7777-4321")
insert_Bank_Account_Relationship_Details(None, "5800-1700-9800-7755", "Credit Card", "4000-1956-5698")
insert_Bank_Account_Relationship_Details(None, "5890-1970-7706-8912", "Add-on Credit Card", "5800-1700-9800-7755")

print("Bank_Account_Relationship_Details table data inserted successfully.")

Bank_Account_Relationship_Details table data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM Bank_Account_Relationship_Details", conn)
display(df)

,Customer_id,Account_Number,Account_type,Linking_Account_Number
0,123001.0,4000-1956-3456,SAVINGS,
1,123001.0,5000-1700-3456,RECURRING DEPOSITS,4000-1956-3456
2,123002.0,4000-1956-2001,SAVINGS,
3,123002.0,5000-1700-5001,RECURRING DEPOSITS,4000-1956-2001
4,123003.0,4000-1956-2900,SAVINGS,
5,123004.0,5000-1700-6091,RECURRING DEPOSITS,4000-1956-2900
6,123004.0,5000-1700-7791,RECURRING DEPOSITS,4000-1956-2900
7,123007.0,5000-1700-9800,SAVINGS,
8,123007.0,4000-1956-9977,RECURRING DEPOSITS,5000-1700-9800
9,NaN,9000-1700-7777-4321,Credit Card,5000-1700-9800
10,NaN,5900-1900-9877-5543,Add-on Credit Card,9000-1700-7777-4321
11,NaN,5800-1700-9800-7755,Credit Card,4000-1956-5698
12,NaN,5890-1970-7706-8912,Add-on Credit Card,5800-1700-9800-7755

In [ ]:
cursor.execute('''
CREATE TABLE BANK_ACCOUNT_TRANSACTION (
    Account_Number VARCHAR(19),
    Transaction_amount DECIMAL(18,2),
    Transcation_channel VARCHAR(18),
    Province VARCHAR(3),
    Transaction_Date DATE
);
''')

conn.commit()

In [ ]:
print("BANK_ACCOUNT_TRANSACTION table created successfully!")

BANK_ACCOUNT_TRANSACTION table created successfully!

In [ ]:
def insert_BANK_ACCOUNT_TRANSACTION(Account_Number, Transaction_amount, Transcation_channel, Province, Transaction_Date):
    cursor.execute("INSERT INTO BANK_ACCOUNT_TRANSACTION VALUES (?, ?, ?, ?, ?)", (Account_Number, Transaction_amount, Transcation_channel, Province, Transaction_Date))
    conn.commit()

In [ ]:
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-3456", -2000, "ATM withdrawl", "CA", "2020-01-13")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-2001", -4000, "POS-Walmart", "MN", "2020-02-14")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-2001", -1600, "UPI transfer", "MN", "2020-01-19")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-2001", -6000, "Bankers cheque", "CA", "2020-03-23")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-2001", -3000, "Net banking", "CA", "2020-04-24")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-2001", 23000, "cheque deposit", "MN", "2020-03-15")
insert_BANK_ACCOUNT_TRANSACTION("5000-1700-6091", 40000, "ECS transfer", "NY", "2020-02-19")
insert_BANK_ACCOUNT_TRANSACTION("5000-1700-7791", 40000, "ECS transfer", "NY", "2020-02-19")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-3401", 8000, "Cash Deposit", "NY", "2020-01-19")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-5102", -6500, "ATM withdrawal", "NY", "2020-03-14")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-5698", -9000, "Cash Deposit", "NY", "2020-03-27")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-9977", 50000, "ECS transfer", "NY", "2020-01-16")
insert_BANK_ACCOUNT_TRANSACTION("9000-1700-7777-4321", -5000, "POS-Walmart", "NY", "2020-02-17")
insert_BANK_ACCOUNT_TRANSACTION("9000-1700-7777-4321", -8000, "Shopping Cart", "MN", "2020-03-13")
insert_BANK_ACCOUNT_TRANSACTION("9000-1700-7777-4321", -2500, "Shopping Cart", "MN", "2020-04-21")
insert_BANK_ACCOUNT_TRANSACTION("5800-1700-9800-7755", -9000, "POS-Walmart", "MN", "2020-04-13")
insert_BANK_ACCOUNT_TRANSACTION("5890-1970-7706-8912", -11000, "Shopping Cart", "NY", "2020-03-12")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-9977", 10000.00, "ECS transfer", "MN", "2020-02-16")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-9977", 40000.00, "ECS transfer", "MN", "2020-03-18")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-9977", 60000.00, "ECS transfer", "MN", "2020-04-18")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-9977", 20000.00, "ECS transfer", "MN", "2020-03-20")
insert_BANK_ACCOUNT_TRANSACTION("4000-1956-9977", 49000.00, "ECS transfer", "MN", "2020-06-18")

print("BANK_ACCOUNT_TRANSACTION table data inserted successfully.")

BANK_ACCOUNT_TRANSACTION table data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM BANK_ACCOUNT_TRANSACTION", conn)
display(df)

,Account_Number,Transaction_amount,Transcation_channel,Province,Transaction_Date
0,4000-1956-3456,-2000,ATM withdrawl,CA,2020-01-13
1,4000-1956-2001,-4000,POS-Walmart,MN,2020-02-14
2,4000-1956-2001,-1600,UPI transfer,MN,2020-01-19
3,4000-1956-2001,-6000,Bankers cheque,CA,2020-03-23
4,4000-1956-2001,-3000,Net banking,CA,2020-04-24
5,4000-1956-2001,23000,cheque deposit,MN,2020-03-15
6,5000-1700-6091,40000,ECS transfer,NY,2020-02-19
7,5000-1700-7791,40000,ECS transfer,NY,2020-02-19
8,4000-1956-3401,8000,Cash Deposit,NY,2020-01-19
9,4000-1956-5102,-6500,ATM withdrawal,NY,2020-03-14
10,4000-1956-5698,-9000,Cash Deposit,NY,2020-03-27
11,4000-1956-9977,50000,ECS transfer,NY,2020-01-16
12,9000-1700-7777-4321,-5000,POS-Walmart,NY,2020-02-17
13,9000-1700-7777-4321,-8000,Shopping Cart,MN,2020-03-13
14,9000-1700-7777-4321,-2500,Shopping Cart,MN,2020-04-21
15,5800-1700-9800-7755,-9000,POS-Walmart,MN,2020-04-13
16,5890-1970-7706-8912,-11000,Shopping Cart,NY,2020-03-12
17,4000-1956-9977,10000,ECS transfer,MN,2020-02-16
18,4000-1956-9977,40000,ECS transfer,MN,2020-03-18
19,4000-1956-9977,60000,ECS transfer,MN,2020-04-18
20,4000-1956-9977,20000,ECS transfer,MN,2020-03-20
21,4000-1956-9977,49000,ECS transfer,MN,2020-06-18

In [ ]:
cursor.execute('''
CREATE TABLE BANK_CUSTOMER_MESSAGES (
    Event VARCHAR(24),
    Customer_message VARCHAR(75),
    Notice_delivery_mode VARCHAR(15)
);
''')

conn.commit()

In [ ]:
print("BANK_CUSTOMER_MESSAGES table created successfully!")

BANK_CUSTOMER_MESSAGES table created successfully!

In [ ]:
def insert_BANK_CUSTOMER_MESSAGES(Event, Customer_message, Notice_delivery_mode):
    cursor.execute("INSERT INTO BANK_CUSTOMER_MESSAGES VALUES (?, ?, ?)", (Event, Customer_message, Notice_delivery_mode))
    conn.commit()

In [ ]:
insert_BANK_CUSTOMER_MESSAGES("Adhoc", "All Banks are closed due to announcement of National strike", "mobile")
insert_BANK_CUSTOMER_MESSAGES("Transaction Limit", "Only limited withdrawals per card are allowed from ATM machines", "mobile")

print("BANK_CUSTOMER_MESSAGES table created and data inserted successfully.")

BANK_CUSTOMER_MESSAGES table created and data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM BANK_CUSTOMER_MESSAGES", conn)
display(df)

,Event,Customer_message,Notice_delivery_mode
0,Adhoc,All Banks are closed due to announcement of Na...,mobile
1,Transaction Limit,Only limited withdrawals per card are allowed ...,mobile

In [ ]:
cursor.execute('''
CREATE TABLE BANK_INTEREST_RATE (
    account_type VARCHAR(24),
    interest_rate DECIMAL(4,2),
    month VARCHAR(2),
    year VARCHAR(4)
);
''')

conn.commit()

In [ ]:
print("BANK_INTEREST RATE table created successfully!")

BANK_INTEREST RATE table created successfully!

In [ ]:
def insert_BANK_INTEREST_RATE(account_type, interest_rate, month, year):
    cursor.execute("INSERT INTO BANK_INTEREST_RATE VALUES (?, ?, ?, ?)", (account_type, interest_rate, month, year))
    conn.commit()

In [ ]:
insert_BANK_INTEREST_RATE("SAVINGS", 0.04, "02", "2020")
insert_BANK_INTEREST_RATE("RECURRING DEPOSITS", 0.07, "02", "2020")
insert_BANK_INTEREST_RATE("PRIVILEGED_INTEREST_RATE", 0.08, "02", "2020")

print("BANK_INTEREST_RATE table data inserted successfully.")

BANK_INTEREST_RATE table data inserted successfully.

In [ ]:
df = pd.read_sql_query("SELECT * FROM BANK_INTEREST_RATE", conn)
display(df)

               account_type  interest_rate month  year
0                   SAVINGS           0.04    02  2020
1        RECURRING DEPOSITS           0.07    02  2020
2  PRIVILEGED_INTEREST_RATE           0.08    02  2020

In [ ]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
display(tables)

                                name
0              BANK_ACCOUNT_DETAILS1
1                      BANK_CUSTOMER
2               BANK_CUSTOMER_EXPORT
3               Bank_Account_Details
4                       BANK_ACCOUNT
5  Bank_Account_Relationship_Details
6           BANK_ACCOUNT_TRANSACTION
7             BANK_CUSTOMER_MESSAGES
8                 BANK_INTEREST_RATE

QUERY 1

In [ ]:
query1 = '''
SELECT
    c.customer_id,
    c.customer_name,
    AVG(a.Balance_amount) AS average_balance
FROM BANK_CUSTOMER c
JOIN Bank_Account_Details a
    ON c.customer_id = a.Customer_id
GROUP BY c.customer_id, c.customer_name;
'''

In [ ]:
df1 = pd.read_sql_query(query1, conn)
display(df1)

   customer_id customer_name  average_balance
0       123001        Oliver     4.800000e+06
1       123002        George     3.950000e+06
2       123003         Harry     7.500000e+05
3       123004          Jack     4.077500e+06
4       123005         Jacob     3.000000e+05
5       123006          Noah     1.516667e+05
6       123007       Charlie     1.845000e+06
7       123008         Robin     0.000000e+00

QUERY 2

In [ ]:
query2 = '''
SELECT
    a.Customer_id,
    a.Account_Number,
    COALESCE(a.Balance_amount, t.Transaction_amount) AS balance_amount
FROM Bank_Account_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
WHERE a.Account_type = 'Credit Card';
'''

In [ ]:
df2 = pd.read_sql_query(query2, conn)
display(df2)

   Customer_id       Account_Number  balance_amount
0       123007  9000-1700-7777-4321               0
1       123007  9000-1700-7777-4321               0
2       123007  9000-1700-7777-4321               0
3       123006  5800-1700-9800-7755               0

QUERY 3

In [ ]:
query3 = '''
SELECT
    a.Account_Number,
    a.Balance_amount,
    t.Transaction_amount,
    t.Transaction_Date
FROM Bank_Account_Details a
JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
WHERE t.Transaction_Date >= '2020-03-01'
AND t.Transaction_Date < '2020-05-01';
'''

In [ ]:
df3 = pd.read_sql_query(query3, conn)
display(df3)

         Account_Number  Balance_amount  Transaction_amount Transaction_Date
0        4000-1956-2001          400000               -6000       2020-03-23
1        4000-1956-2001          400000               -3000       2020-04-24
2        4000-1956-2001          400000               23000       2020-03-15
3        4000-1956-5102          300000               -6500       2020-03-14
4        4000-1956-5698          455000               -9000       2020-03-27
5   9000-1700-7777-4321               0               -8000       2020-03-13
6   9000-1700-7777-4321               0               -2500       2020-04-21
7   5800-1700-9800-7755               0               -9000       2020-04-13
8   5890-1970-7706-8912               0              -11000       2020-03-12
9        4000-1956-9977         7025000               40000       2020-03-18
10       4000-1956-9977         7025000               60000       2020-04-18
11       4000-1956-9977         7025000               20000       2020-03-20

QUERY 3

In [ ]:
query4 = '''
SELECT
    c.customer_id,
    a.Account_Number,
    a.Balance_amount,
    t.Transaction_amount,
    t.Transaction_Date
FROM BANK_CUSTOMER c
JOIN Bank_Account_Details a
    ON c.customer_id = a.Customer_id
JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
WHERE t.Transaction_Date < '2020-03-01'
   OR t.Transaction_Date >= '2020-04-01';
'''

In [ ]:
df4 = pd.read_sql_query(query4, conn)
display(df4)

,customer_id,Account_Number,Balance_amount,Transaction_amount,Transaction_Date
0,123001,4000-1956-3456,200000,-2000,2020-01-13
1,123002,4000-1956-2001,400000,-4000,2020-02-14
2,123002,4000-1956-2001,400000,-1600,2020-01-19
3,123002,4000-1956-2001,400000,-3000,2020-04-24
4,123004,5000-1700-6091,7500000,40000,2020-02-19
5,123004,4000-1956-3401,655000,8000,2020-01-19
6,123007,4000-1956-9977,7025000,50000,2020-01-16
7,123007,9000-1700-7777-4321,0,-5000,2020-02-17
8,123007,9000-1700-7777-4321,0,-2500,2020-04-21
9,123006,5800-1700-9800-7755,0,-9000,2020-04-13
10,123007,4000-1956-9977,7025000,10000,2020-02-16
11,123007,4000-1956-9977,7025000,60000,2020-04-18
12,123007,4000-1956-9977,7025000,49000,2020-06-18

QUERY 5

In [ ]:
query5 = '''
SELECT
    a.Customer_id,
    a.Account_Number,
    a.Balance_amount,
    t.Transaction_amount,
    t.Transaction_Date
FROM Bank_Account_Details a
JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
WHERE t.Transaction_Date >= '2020-01-01'
AND t.Transaction_Date < '2020-04-01';
'''

In [ ]:
df5 = pd.read_sql_query(query5, conn)
display(df5)

,Customer_id,Account_Number,Balance_amount,Transaction_amount,Transaction_Date
0,123001,4000-1956-3456,200000,-2000,2020-01-13
1,123002,4000-1956-2001,400000,-4000,2020-02-14
2,123002,4000-1956-2001,400000,-1600,2020-01-19
3,123002,4000-1956-2001,400000,-6000,2020-03-23
4,123002,4000-1956-2001,400000,23000,2020-03-15
5,123004,5000-1700-6091,7500000,40000,2020-02-19
6,123004,4000-1956-3401,655000,8000,2020-01-19
7,123005,4000-1956-5102,300000,-6500,2020-03-14
8,123006,4000-1956-5698,455000,-9000,2020-03-27
9,123007,4000-1956-9977,7025000,50000,2020-01-16
10,123007,9000-1700-7777-4321,0,-5000,2020-02-17
11,123007,9000-1700-7777-4321,0,-8000,2020-03-13
12,123006,5890-1970-7706-8912,0,-11000,2020-03-12
13,123007,4000-1956-9977,7025000,10000,2020-02-16
14,123007,4000-1956-9977,7025000,40000,2020-03-18
15,123007,4000-1956-9977,7025000,20000,2020-03-20

QUERY 6

In [ ]:
query6 = '''
SELECT
    a.Account_Number,
    m.Event,
    m.Customer_message
FROM Bank_Account_Details a
CROSS JOIN BANK_CUSTOMER_MESSAGES m
WHERE a.Account_type = 'SAVINGS'
AND m.Event = 'Adhoc';
'''

In [ ]:
df6 = pd.read_sql_query(query6, conn)
display(df6)

   Account_Number  Event                                   Customer_message
0  4000-1956-3456  Adhoc  All Banks are closed due to announcement of Na...
1  4000-1956-2001  Adhoc  All Banks are closed due to announcement of Na...
2  4000-1956-2900  Adhoc  All Banks are closed due to announcement of Na...
3  4000-1956-3401  Adhoc  All Banks are closed due to announcement of Na...
4  4000-1956-5102  Adhoc  All Banks are closed due to announcement of Na...
5  4000-1956-5698  Adhoc  All Banks are closed due to announcement of Na...
6  5000-1700-9800  Adhoc  All Banks are closed due to announcement of Na...
7  5000-1700-7755  Adhoc  All Banks are closed due to announcement of Na...

QUERY 7

In [ ]:
query7 = '''
SELECT
    a.Customer_id,
    a.Account_Number,
    a.Account_type,
    a.Balance_amount +
    COALESCE(
        SUM(
            CASE
                WHEN t.Transaction_amount < 0
                THEN t.Transaction_amount
                ELSE 0
            END
        ), 0
    ) AS deducted_balance_amount
FROM Bank_Account_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
WHERE a.Relationship_type = 'P'
GROUP BY
    a.Customer_id,
    a.Account_Number,
    a.Account_type,
    a.Balance_amount;
'''

In [ ]:
df7 = pd.read_sql_query(query7, conn)
display(df7)

   Customer_id       Account_Number Account_type  deducted_balance_amount
0       123001       4000-1956-3456      SAVINGS                   198000
1       123002       4000-1956-2001      SAVINGS                   385400
2       123003       4000-1956-2900      SAVINGS                   750000
3       123004       4000-1956-3401      SAVINGS                   655000
4       123005       4000-1956-5102      SAVINGS                   293500
5       123006       4000-1956-5698      SAVINGS                   446000
6       123006  5800-1700-9800-7755  Credit Card                    -9000
7       123007       5000-1700-9800      SAVINGS                   355000
8       123007  9000-1700-7777-4321  Credit Card                   -15500
9       123008       5000-1700-7755      SAVINGS                        0

QUERY 8

In [ ]:
query8a = '''
SELECT
    a.Account_Number,
    a.Account_type,
    t.Transaction_amount
FROM Bank_Account_Relationship_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number;
'''

In [ ]:
df8a = pd.read_sql_query(query8a, conn)
display(df8a)

         Account_Number        Account_type  Transaction_amount
0        4000-1956-3456             SAVINGS             -2000.0
1        5000-1700-3456  RECURRING DEPOSITS                 NaN
2        4000-1956-2001             SAVINGS             -6000.0
3        4000-1956-2001             SAVINGS             -4000.0
4        4000-1956-2001             SAVINGS             -3000.0
5        4000-1956-2001             SAVINGS             -1600.0
6        4000-1956-2001             SAVINGS             23000.0
7        5000-1700-5001  RECURRING DEPOSITS                 NaN
8        4000-1956-2900             SAVINGS                 NaN
9        5000-1700-6091  RECURRING DEPOSITS             40000.0
10       5000-1700-7791  RECURRING DEPOSITS             40000.0
11       5000-1700-9800             SAVINGS                 NaN
12       4000-1956-9977  RECURRING DEPOSITS             10000.0
13       4000-1956-9977  RECURRING DEPOSITS             20000.0
14       4000-1956-9977  RECURRING DEPOSITS             40000.0
15       4000-1956-9977  RECURRING DEPOSITS             49000.0
16       4000-1956-9977  RECURRING DEPOSITS             50000.0
17       4000-1956-9977  RECURRING DEPOSITS             60000.0
18  9000-1700-7777-4321         Credit Card             -8000.0
19  9000-1700-7777-4321         Credit Card             -5000.0
20  9000-1700-7777-4321         Credit Card             -2500.0
21  5900-1900-9877-5543  Add-on Credit Card                 NaN
22  5800-1700-9800-7755         Credit Card             -9000.0
23  5890-1970-7706-8912  Add-on Credit Card            -11000.0

In [ ]:
query8b = '''
SELECT
    a.Account_Number,
    a.Account_type,
    t.Transaction_amount,
    a.Linking_Account_Number,
    b.Account_type AS Linking_Account_type
FROM Bank_Account_Relationship_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
LEFT JOIN Bank_Account_Relationship_Details b
    ON a.Linking_Account_Number = b.Account_Number;
'''

In [ ]:
df8b = pd.read_sql_query(query8b, conn)
display(df8b)

,Account_Number,Account_type,Transaction_amount,Linking_Account_Number,Linking_Account_type
0,4000-1956-3456,SAVINGS,-2000.0,,None
1,5000-1700-3456,RECURRING DEPOSITS,NaN,4000-1956-3456,SAVINGS
2,4000-1956-2001,SAVINGS,-6000.0,,None
3,4000-1956-2001,SAVINGS,-4000.0,,None
4,4000-1956-2001,SAVINGS,-3000.0,,None
5,4000-1956-2001,SAVINGS,-1600.0,,None
6,4000-1956-2001,SAVINGS,23000.0,,None
7,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS
8,4000-1956-2900,SAVINGS,NaN,,None
9,5000-1700-6091,RECURRING DEPOSITS,40000.0,4000-1956-2900,SAVINGS
10,5000-1700-7791,RECURRING DEPOSITS,40000.0,4000-1956-2900,SAVINGS
11,5000-1700-9800,SAVINGS,NaN,,None
12,4000-1956-9977,RECURRING DEPOSITS,10000.0,5000-1700-9800,SAVINGS
13,4000-1956-9977,RECURRING DEPOSITS,20000.0,5000-1700-9800,SAVINGS
14,4000-1956-9977,RECURRING DEPOSITS,40000.0,5000-1700-9800,SAVINGS
15,4000-1956-9977,RECURRING DEPOSITS,49000.0,5000-1700-9800,SAVINGS
16,4000-1956-9977,RECURRING DEPOSITS,50000.0,5000-1700-9800,SAVINGS
17,4000-1956-9977,RECURRING DEPOSITS,60000.0,5000-1700-9800,SAVINGS
18,9000-1700-7777-4321,Credit Card,-8000.0,5000-1700-9800,SAVINGS
19,9000-1700-7777-4321,Credit Card,-5000.0,5000-1700-9800,SAVINGS
20,9000-1700-7777-4321,Credit Card,-2500.0,5000-1700-9800,SAVINGS
21,5900-1900-9877-5543,Add-on Credit Card,NaN,9000-1700-7777-4321,Credit Card
22,5800-1700-9800-7755,Credit Card,-9000.0,4000-1956-5698,None
23,5890-1970-7706-8912,Add-on Credit Card,-11000.0,5800-1700-9800-7755,Credit Card

In [ ]:
query9a = '''
SELECT
    a.Account_Number,
    a.Account_type,
    t.Transaction_amount
FROM Bank_Account_Relationship_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number;
'''

In [ ]:
df9a = pd.read_sql_query(query9a, conn)
display(df9a)

         Account_Number        Account_type  Transaction_amount
0        4000-1956-3456             SAVINGS             -2000.0
1        5000-1700-3456  RECURRING DEPOSITS                 NaN
2        4000-1956-2001             SAVINGS             -6000.0
3        4000-1956-2001             SAVINGS             -4000.0
4        4000-1956-2001             SAVINGS             -3000.0
5        4000-1956-2001             SAVINGS             -1600.0
6        4000-1956-2001             SAVINGS             23000.0
7        5000-1700-5001  RECURRING DEPOSITS                 NaN
8        4000-1956-2900             SAVINGS                 NaN
9        5000-1700-6091  RECURRING DEPOSITS             40000.0
10       5000-1700-7791  RECURRING DEPOSITS             40000.0
11       5000-1700-9800             SAVINGS                 NaN
12       4000-1956-9977  RECURRING DEPOSITS             10000.0
13       4000-1956-9977  RECURRING DEPOSITS             20000.0
14       4000-1956-9977  RECURRING DEPOSITS             40000.0
15       4000-1956-9977  RECURRING DEPOSITS             49000.0
16       4000-1956-9977  RECURRING DEPOSITS             50000.0
17       4000-1956-9977  RECURRING DEPOSITS             60000.0
18  9000-1700-7777-4321         Credit Card             -8000.0
19  9000-1700-7777-4321         Credit Card             -5000.0
20  9000-1700-7777-4321         Credit Card             -2500.0
21  5900-1900-9877-5543  Add-on Credit Card                 NaN
22  5800-1700-9800-7755         Credit Card             -9000.0
23  5890-1970-7706-8912  Add-on Credit Card            -11000.0

In [ ]:
query9b = '''
SELECT
    a.Account_Number,
    a.Account_type,
    t.Transaction_amount,
    a.Linking_Account_Number,
    b.Account_type AS Linking_Account_type
FROM Bank_Account_Relationship_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
LEFT JOIN Bank_Account_Relationship_Details b
    ON a.Linking_Account_Number = b.Account_Number;
'''

In [ ]:
df9b = pd.read_sql_query(query9b, conn)
display(df9b)

,Account_Number,Account_type,Transaction_amount,Linking_Account_Number,Linking_Account_type
0,4000-1956-3456,SAVINGS,-2000.0,,None
1,5000-1700-3456,RECURRING DEPOSITS,NaN,4000-1956-3456,SAVINGS
2,4000-1956-2001,SAVINGS,-6000.0,,None
3,4000-1956-2001,SAVINGS,-4000.0,,None
4,4000-1956-2001,SAVINGS,-3000.0,,None
5,4000-1956-2001,SAVINGS,-1600.0,,None
6,4000-1956-2001,SAVINGS,23000.0,,None
7,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS
8,4000-1956-2900,SAVINGS,NaN,,None
9,5000-1700-6091,RECURRING DEPOSITS,40000.0,4000-1956-2900,SAVINGS
10,5000-1700-7791,RECURRING DEPOSITS,40000.0,4000-1956-2900,SAVINGS
11,5000-1700-9800,SAVINGS,NaN,,None
12,4000-1956-9977,RECURRING DEPOSITS,10000.0,5000-1700-9800,SAVINGS
13,4000-1956-9977,RECURRING DEPOSITS,20000.0,5000-1700-9800,SAVINGS
14,4000-1956-9977,RECURRING DEPOSITS,40000.0,5000-1700-9800,SAVINGS
15,4000-1956-9977,RECURRING DEPOSITS,49000.0,5000-1700-9800,SAVINGS
16,4000-1956-9977,RECURRING DEPOSITS,50000.0,5000-1700-9800,SAVINGS
17,4000-1956-9977,RECURRING DEPOSITS,60000.0,5000-1700-9800,SAVINGS
18,9000-1700-7777-4321,Credit Card,-8000.0,5000-1700-9800,SAVINGS
19,9000-1700-7777-4321,Credit Card,-5000.0,5000-1700-9800,SAVINGS
20,9000-1700-7777-4321,Credit Card,-2500.0,5000-1700-9800,SAVINGS
21,5900-1900-9877-5543,Add-on Credit Card,NaN,9000-1700-7777-4321,Credit Card
22,5800-1700-9800-7755,Credit Card,-9000.0,4000-1956-5698,None
23,5890-1970-7706-8912,Add-on Credit Card,-11000.0,5800-1700-9800-7755,Credit Card

In [ ]:
query9c = '''
SELECT
    a.Account_Number,
    a.Account_type,
    t.Transaction_amount,
    a.Linking_Account_Number,
    b.Account_type AS Linking_Account_type,
    lt.Transaction_amount AS Linking_Transaction_amount
FROM Bank_Account_Relationship_Details a
LEFT JOIN BANK_ACCOUNT_TRANSACTION t
    ON a.Account_Number = t.Account_Number
LEFT JOIN Bank_Account_Relationship_Details b
    ON a.Linking_Account_Number = b.Account_Number
LEFT JOIN BANK_ACCOUNT_TRANSACTION lt
    ON a.Linking_Account_Number = lt.Account_Number;
'''

In [ ]:
df9c = pd.read_sql_query(query9c, conn)
display(df9c)

,Account_Number,Account_type,Transaction_amount,Linking_Account_Number,Linking_Account_type,Linking_Transaction_amount
0,4000-1956-3456,SAVINGS,-2000.0,,None,NaN
1,5000-1700-3456,RECURRING DEPOSITS,NaN,4000-1956-3456,SAVINGS,-2000.0
2,4000-1956-2001,SAVINGS,-6000.0,,None,NaN
3,4000-1956-2001,SAVINGS,-4000.0,,None,NaN
4,4000-1956-2001,SAVINGS,-3000.0,,None,NaN
5,4000-1956-2001,SAVINGS,-1600.0,,None,NaN
6,4000-1956-2001,SAVINGS,23000.0,,None,NaN
7,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS,-6000.0
8,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS,-4000.0
9,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS,-3000.0
10,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS,-1600.0
11,5000-1700-5001,RECURRING DEPOSITS,NaN,4000-1956-2001,SAVINGS,23000.0
12,4000-1956-2900,SAVINGS,NaN,,None,NaN
13,5000-1700-6091,RECURRING DEPOSITS,40000.0,4000-1956-2900,SAVINGS,NaN
14,5000-1700-7791,RECURRING DEPOSITS,40000.0,4000-1956-2900,SAVINGS,NaN
15,5000-1700-9800,SAVINGS,NaN,,None,NaN
16,4000-1956-9977,RECURRING DEPOSITS,10000.0,5000-1700-9800,SAVINGS,NaN
17,4000-1956-9977,RECURRING DEPOSITS,20000.0,5000-1700-9800,SAVINGS,NaN
18,4000-1956-9977,RECURRING DEPOSITS,40000.0,5000-1700-9800,SAVINGS,NaN
19,4000-1956-9977,RECURRING DEPOSITS,49000.0,5000-1700-9800,SAVINGS,NaN
20,4000-1956-9977,RECURRING DEPOSITS,50000.0,5000-1700-9800,SAVINGS,NaN
21,4000-1956-9977,RECURRING DEPOSITS,60000.0,5000-1700-9800,SAVINGS,NaN
22,9000-1700-7777-4321,Credit Card,-8000.0,5000-1700-9800,SAVINGS,NaN
23,9000-1700-7777-4321,Credit Card,-5000.0,5000-1700-9800,SAVINGS,NaN
24,9000-1700-7777-4321,Credit Card,-2500.0,5000-1700-9800,SAVINGS,NaN
25,5900-1900-9877-5543,Add-on Credit Card,NaN,9000-1700-7777-4321,Credit Card,-8000.0
26,5900-1900-9877-5543,Add-on Credit Card,NaN,9000-1700-7777-4321,Credit Card,-5000.0
27,5900-1900-9877-5543,Add-on Credit Card,NaN,9000-1700-7777-4321,Credit Card,-2500.0
28,5800-1700-9800-7755,Credit Card,-9000.0,4000-1956-5698,None,-9000.0
29,5890-1970-7706-8912,Add-on Credit Card,-11000.0,5800-1700-9800-7755,Credit Card,-9000.0

QUERY 10

In [ ]:
query10 = '''
SELECT DISTINCT
    s.Customer_id,
    s.Account_Number AS Savings_Account,
    c.Account_Number AS Credit_Card,
    a.Account_Number AS Add_on_Credit_Card
FROM Bank_Account_Relationship_Details s
JOIN Bank_Account_Relationship_Details c
    ON s.Account_Number = c.Linking_Account_Number
JOIN Bank_Account_Relationship_Details a
    ON c.Account_Number = a.Linking_Account_Number
WHERE s.Account_type = 'SAVINGS'
AND c.Account_type = 'Credit Card'
AND a.Account_type = 'Add-on Credit Card';
'''

In [ ]:
df10 = pd.read_sql_query(query10, conn)
display(df10)

   Customer_id Savings_Account          Credit_Card   Add_on_Credit_Card
0       123007  5000-1700-9800  9000-1700-7777-4321  5900-1900-9877-5543

QUERY 11

In [ ]:
query11 = '''
SELECT
    s.Account_Number AS Savings_Account,
    c.Account_Number AS Credit_Card,
    SUM(t.Transaction_amount) AS Credit_Aggregate
FROM Bank_Account_Relationship_Details s
JOIN Bank_Account_Relationship_Details c
    ON s.Account_Number = c.Linking_Account_Number
JOIN BANK_ACCOUNT_TRANSACTION t
    ON c.Account_Number = t.Account_Number
WHERE s.Account_type = 'SAVINGS'
AND c.Account_type = 'Credit Card'
GROUP BY s.Account_Number, c.Account_Number;
'''

In [ ]:
df11 = pd.read_sql_query(query11, conn)
display(df11)

  Savings_Account          Credit_Card  Credit_Aggregate
0  5000-1700-9800  9000-1700-7777-4321            -15500